### ISSUE TITLE
RuntimeError: populate() isn't reentrant

### ISSUE THREAD

**Issue by songcser** [coderholic/django-cities#121]
"cities" in INSTALLED_APPS, I get this exception

```

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 78, in populate
    raise RuntimeError("populate() isn't reentrant")

```

**Comment by blag** [comment]
Did you ever get this working?

If not, can you answer the following questions:

1. What version of Django?
2. What command were you trying to run?
3. What code in django-cities do you think is responsible for this?

**Comment by blag** [comment]
You haven't responded, and this doesn't look like it's a bug in django-cities, so I'm going to close this issue. Feel free to reopen with more information or if you trace the issue back to django-cities.
