### ISSUE TITLE
django-cities crashes on syncdb with a fresh install of Django 1.6.2, GeoDjango, on Windows

### ISSUE THREAD

**Issue by coderam** [coderholic/django-cities#57]
Please be advised, I get the following traceback upon a syncdb of the "cities" app alongside the "geodjango" pre-requisite:

(funretire) C:\Users\code\workspace\funretire\src>python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management\base.py", line 242, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management\base.py", line 284, in execute
    self.validate()
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management\base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management\validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\db\models\loading.py", line 196, in get_app_errors
    self._populate()
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\db\models\loading.py", line 78, in _populate
    self.load_app(app_name)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\db\models\loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Users\code\Envs\funretire\lib\site-packages\cities\models.py", line 2, in <module>
    from django.contrib.gis.db import models
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\db\models__init__.py", line 8, in <module>
    from django.contrib.gis.db.models.manager import GeoManager
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\db\models\manager.py", line 2, in <module>
    from django.contrib.gis.db.models.query import GeoQuerySet
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\db\models\query.py", line 6, in <module>
    from django.contrib.gis.db.models.fields import get_srid_info, PointField, LineStringField
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\db\models\fields.py", line 4, in <module>
    from django.contrib.gis import forms
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\forms__init__.py", line 2, in <module>
    from .fields import (GeometryField, GeometryCollectionField, PointField,
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\forms\fields.py", line 11, in <module>
    from django.contrib.gis.geos import GEOSException, GEOSGeometry, fromstr
ImportError: cannot import name GEOSException

(funretire) C:\Users\code\workspace\funretire\src>python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management\base.py", line 242, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management\base.py", line 284, in execute
    self.validate()
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management\base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\core\management\validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\db\models\loading.py", line 196, in get_app_errors
    self._populate()
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\db\models\loading.py", line 78, in _populate
    self.load_app(app_name)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\db\models\loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Users\code\Envs\funretire\lib\site-packages\cities\models.py", line 2, in <module>
    from django.contrib.gis.db import models
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\db\models__init__.py", line 8, in <module>
    from django.contrib.gis.db.models.manager import GeoManager
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\db\models\manager.py", line 2, in <module>
    from django.contrib.gis.db.models.query import GeoQuerySet
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\db\models\query.py", line 6, in <module>
    from django.contrib.gis.db.models.fields import get_srid_info, PointField, LineStringField
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\db\models\fields.py", line 4, in <module>
    from django.contrib.gis import forms
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\forms__init__.py", line 2, in <module>
    from .fields import (GeometryField, GeometryCollectionField, PointField,
  File "C:\Users\code\Envs\funretire\lib\site-packages\django\contrib\gis\forms\fields.py", line 11, in <module>
    from django.contrib.gis.geos import GEOSException, GEOSGeometry, fromstr
ImportError: cannot import name GEOSException

When I remove the Django-cities app from INSTALLED_APPS, manage.py syncdb seems to work just fine:

(funretire) C:\Users\code\workspace\funretire\src>python manage.py syncdb
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

**Comment by imposeren** [comment]
Have you installed GEOS ? you should install both OS library and python module:

```bash
pip install pygdal==1.11.0
```

Note that pygdal version and version on your OS should match. I don't know how to install GDAL on Windows but you can try something from here: https://trac.osgeo.org/gdal/wiki/DownloadingGdalBinaries

**Comment by imposeren** [comment]
I think that pygdal will not work on windows. You can try this solution: http://gis.stackexchange.com/a/2279

**Comment by blag** [comment]
Is this still an issue?

**Comment by blag** [comment]
Since this is for a version of Django that is no longer supported, I'm going to close this issue. Please reopen if currently supported versions of Django have the same issue.

**Comment by coderam** [comment]
Thank you
