### ISSUE TITLE
ImportError: cannot import name 'force_unicode' (with python 3.4)

### ISSUE THREAD

**Issue by CosminG** [coderholic/django-cities#67]
I use django 1.7 and python 3.4

./manage.py migrate
I get this:
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cosmin/.v/gasit/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/cosmin/.v/gasit/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/cosmin/.v/gasit/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/cosmin/.v/gasit/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/cosmin/.v/gasit/lib/python3.4/site-packages/django/apps/config.py", line 197, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/cosmin/.v/gasit/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/cosmin/.v/gasit/lib/python3.4/site-packages/cities/models.py", line 1, in <module>
    from django.utils.encoding import force_unicode
ImportError: cannot import name 'force_unicode'

**Comment by mitsest** [comment]
Can't see python 3 support here : https://pypi.python.org/pypi/django-cities

Is this true?
Did anyone manage to make this work with python 3?

**Comment by nkumar15** [comment]
Did anyone looking into this issue?

**Comment by bashu** [comment]
fixed, see related PR
