### ISSUE TITLE
ValueError: could not convert string to float: T

### ISSUE THREAD

**Issue by chokosabe** [coderholic/django-cities#75]
Getting the output below when running manage.py cities.
Could it be a problem with python versions?

INFO Downloading: allCountries.zip
INFO Importing country data
INFO {'code': '2986043', 'postalCodeRegex': '0', 'name': '42.64991', 'codeNum': 'Pic de Font Blanca', 'area': 'T', 'geonameid': '2860', 'currencyCode': '00', 'tld': '', 'languages': '', 'phone': '', 'neighbours': 'Europe/Andorra', 'code3': 'Pic de Font Blanca', 'fips': 'Pic de Font Blanca,Pic du Port', 'capital': '1.53335', 'postalCodeFormat': '', 'currencyName': '', 'continent': 'AD', 'equivalentFips': '2014-11-05\n', 'population': 'PK'}
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(_args, *_options)
  File "/home/vagrant/env/local/lib/python2.7/site-packages/cities/management/commands/cities.py", line 68, in handle
    func()
  File "/home/vagrant/env/local/lib/python2.7/site-packages/cities/management/commands/cities.py", line 179, in import_country
    country.area = int(float(item['area'])) if item['area'] else None
ValueError: could not convert string to float: T

**Comment by imposeren** [comment]
looks like a problem in data file

**Comment by coderholic** [comment]
Can you confirm is this is still a problem or not with 0.4.2 from pypi?

**Comment by blag** [comment]
I just released version 0.5 to PyPI and it fixes a **bunch** of issues. Closing, but if you are still having this issue, please reopen it.
