### ISSUE TITLE
Exception: File not found and download failed: countryInfo.txt

### ISSUE THREAD

**Issue by mbambafd** [coderholic/django-cities#80]
i use python 3.4, with django 1.8.2
i have installed django-cities and i correct all tiny errors 
that's is the part of my settings.py project:
# Cities settings
CITIES_FILES = {
    'city': {
        'filename': 'CM.zip',
        'urls': ['http://download.geonames.org/export/dump/' + '{filename}']
    },
}

CITIES_LOCALES = ['en-CM', 'und', 'LANGUAGES']
CITIES_PLUGINS = [
    'cities.plugin.postal_code_ca.Plugin',
]
when i run this: manage.py cities --force --import=all 
i get this error:
Web file not found: countryInfo.txt. Tried URLs:
http://download.geonames.org/export/dump/countryInfo.txt
Assuming file is up-to-date
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "c:\Python34\lib\site-packages\django\core\management\__init__.py", line
338, in execute_from_command_line
    utility.execute()
  File "c:\Python34\lib\site-packages\django\core\management\__init__.py", line
330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\Python34\lib\site-packages\django\core\management\base.py", line 390,
 in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\Python34\lib\site-packages\django\core\management\base.py", line 441,
 in execute
    output = self.handle(*args, **options)
  File "c:\Python34\lib\site-packages\django_cities-0.4.1-py3.4.egg\cities\manag
ement\commands\cities.py", line 68, in handle
    func()
  File "c:\Python34\lib\site-packages\django_cities-0.4.1-py3.4.egg\cities\manag
ement\commands\cities.py", line 150, in import_country
    uptodate = self.download('country')
  File "c:\Python34\lib\site-packages\django_cities-0.4.1-py3.4.egg\cities\manag
ement\commands\cities.py", line 120, in download
    raise Exception("File not found and download failed: " + filename)
Exception: File not found and download failed: countryInfo.txt
Pleaseme need help !

**Comment by imposeren** [comment]
maybe geonames was down?

**Comment by mbambafd** [comment]
No i have solved it ! if  my solution interrest you <a href="https://github.com/coderholic/django-cities/issues/78">See it here</a>

**Comment by bashu** [comment]
solved, see related PR
