### ISSUE TITLE
Cannot install via Pip

### ISSUE THREAD

**Issue by stringsonfire** [coderholic/django-cities#90]
I'm trying to install django-cities 0.4.1 on Windows 8 with Python 3.4 and Pip 7.1.2, but hit this error:

    C:\Windows\system32>pip install django-cities
    Collecting django-cities
      Downloading django-cities-0.4.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "C:\Users\Daniel\AppData\Local\Temp\pip-build-7212nqq8\django-cities\setup.py", line 21, in <module>
            long_description=read('README.md'),
          File "C:\Users\Daniel\AppData\Local\Temp\pip-build-7212nqq8\django-cities\setup.py", line 9, in read
            return open(os.path.join(os.path.dirname(__file__), fname)).read()
          File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
            return codecs.charmap_decode(input,self.errors,decoding_table)[0]
        UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 4588: character maps to <undefined>

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\Daniel\AppData\Local\Temp\pip-build-7212nqq8\django-cities

I navigated to the unpacked temp folder Pip created, edited setup.py line 9 as follows, used `pip install .`, and it installed perfectly:

    return open(os.path.join(os.path.dirname(__file__), fname), encoding="utf-8").read()

I don't think `encoding` is backwards compatible with Python 2, but I'm confident there's a way to make it work simply with both Python 2 and 3.

This is applicable to the current Master repo, not just what I got from pip.

**Comment by stringsonfire** [comment]
Is it because the encoding for open() isn't set, so it's picking the default for my OS?

**Comment by stringsonfire** [comment]
Confirmed. Navigated to the unpacked temp folder Pip created, edited setup.py line 9 as follows, used `pip install .`, and it installed perfectly:

    return open(os.path.join(os.path.dirname(__file__), fname), encoding="utf-8").read()
