### ISSUE TITLE
Manage.py Issue

### ISSUE THREAD

**Issue by stringsonfire** [coderholic/django-cities#93]
I got this error, and the comma does exist in my pip-installed copy, but here in the github repo this appears fine. Did I somehow not download the latest version?

    c:\web\tabletop\src>python manage.py cities --import=all
    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 190, in fetch_command
        klass = load_command_class(app_name, subcommand)
      File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 40, in load_command_class
        module = import_module('%s.management.commands.%s' % (app_name, name))
      File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1467, in exec_module
      File "<frozen importlib._bootstrap>", line 1572, in get_code
      File "<frozen importlib._bootstrap>", line 1532, in source_to_code
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "C:\Python34\lib\site-packages\cities\management\commands\cities.py", line 492
        except Exception, e:
                        ^
    SyntaxError: invalid syntax

**Comment by stringsonfire** [comment]
See https://github.com/coderholic/django-cities/issues/94

**Comment by coderholic** [comment]
Can you confirm is this is still a problem or not with 0.4.2 from pypi?

**Comment by stringsonfire** [comment]
This was resolved when I installed the latest version from the github repo, so shouldn't be an issue with 0.4.2.
